version: "3.9"

services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: lib-t3
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - lib-net

  db:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=libdb
    networks:
      - lib-net
    volumes:
      - lib:/var/lib/postgresql

networks:
  lib-net:
volumes:
  lib:
