version: "3.9"

services:
  lib-app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "2000:3000"
    image: lib-t3
    environment:
      - DATABASE_URL=$DATABASE_URL
    command: sh -c "./wait-for-it.sh db:5432 -- npx prisma db push && node server.js"
    depends_on:
      - lib-db
    networks:
      - lib_net

  lib-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    networks:
      - lib_net
    volumes:
      - lib:/var/lib/postgresql

networks:
  lib_net:
volumes:
  lib:
